#!/bin/sh

PATH_LISTS='/opt/lists'
PATH_WORDLISTS="${PATH_LISTS}/wordlists"
PATH_RESOLVERS="${PATH_LISTS}/resolvers"
PATH_AMASS_WORDLISTS="${PATH_WORDLISTS}/amass"
PATH_BRUTESPRAY_WORDLISTS="${PATH_WORDLISTS}/brutespray"
PATH_SECLISTS_WORDLISTS="${PATH_WORDLISTS}/seclists"
PATH_KALILISTS_WORDLISTS="${PATH_WORDLISTS}/kalilists"

PATH_AMASS='/opt/amass'
PATH_METABIGOR='/opt/metabigor'
PATH_GOSPIDER='/opt/gospider'
PATH_HAKRAWLER='/opt/hakrawler'
PATH_GITHUB_SUBDOMAINS='/opt/github-subdomains'
PATH_ASSETFINDER='/opt/assetfinder'
PATH_HTTPROBE='/opt/httprobe'
PATH_SUBOVER='/opt/subover'
PATH_FFUF='/opt/ffuf'
PATH_ASNLOOKUP='/opt/asnlookup'
PATH_DOMLINK='/opt/domlink'
PATH_SUBDOMAINIZER='/opt/subdomainizer'
PATH_SUBFINDER='/opt/subfinder'
PATH_MASSDNS='/opt/massdns'
PATH_MASSCAN='/opt/masscan'
PATH_DNMASSCAN='/opt/dnmasscan'
PATH_BRUTESPRAY='/opt/brutespray'
PATH_GETRELATIONSHIP='/opt/getrelationship'
PATH_FAVFREAK='/opt/favfreak'
PATH_SHOSUBGO='/opt/shosubgo'
PATH_SUBSCRAPER='/opt/subscraper'
PATH_EYEWITNESS='/opt/eyewitness'
PATH_GITHUB_SEARCH='/opt/github-search'
PATH_DNSVALIDATOR='/opt/dnsvalidator'
PATH_LINKFINDER='/opt/linkfinder'
PATH_NUCLEI='/opt/nuclei'

PATH_AMASS_CONFIG="${PATH_AMASS}/config.ini"
PATH_DOMLINK_CONFIG="${PATH_DOMLINK}/domLink.cfg"
PATH_SHOSUBGO_CONFIG="${PATH_SHOSUBGO}/shosubgo.sh"
PATH_SUBSCRAPER_CONFIG="${PATH_SUBSCRAPER}/subscraper.sh"
PATH_SUBFINDER_CONFIG="${PATH_SUBFINDER}/config.yaml"
