BINARYEDGE_API_KEY=${BINARYEDGE_API_KEY:-BINARYEDGE_API_KEY}
CENSYS_API_KEY=${CENSYS_API_KEY:-CENSYS_API_KEY}
CENSYS_SECRET=${CENSYS_SECRET:-CENSYS_SECRET}
GITHUB_API_KEY=${GITHUB_API_KEY:-GITHUB_API_KEY}
INTELX_API_KEY=${INTELX_API_KEY:-INTELX_API_KEY}
INTELX_HOST=${INTELX_HOST:-INTELX_HOST}
PASSIVETOTAL_USERNAME=${PASSIVETOTAL_USERNAME:-PASSIVETOTAL_USERNAME}
PASSIVETOTAL_PASSWORD=${PASSIVETOTAL_PASSWORD:-PASSIVETOTAL_PASSWORD}
RECONDEV_API_KEY=${RECONDEV_API_KEY:-RECONDEV_API_KEY}
SECURITYTRAILS_API_KEY=${SECURITYTRAILS_API_KEY:-SECURITYTRAILS_API_KEY}
SHODAN_API_KEY=${SHODAN_API_KEY:-SHODAN_API_KEY}
SPYSE_API_KEY=${SPYSE_API_KEY:-SPYSE_API_KEY}
URLSCAN_API_KEY=${URLSCAN_API_KEY:-URLSCAN_API_KEY}
VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY:-VIRUSTOTAL_API_KEY}
ZOOMEYE_USERNAME=${ZOOMEYE_USERNAME:-ZOOMEYE_USERNAME}
ZOOMEYE_PASSWORD=${ZOOMEYE_PASSWORD:-ZOOMEYE_PASSWORD}

install() {(
    set -e
    mkdir -p "$(dirname ${PATH_SUBFINDER_CONFIG})"
    sed "s|BINARYEDGE_API_KEY|${BINARYEDGE_API_KEY}|g" "${MAKE_CONFIG_SCRIPT_DIR}/subfinder/config/config.yaml" |
    sed "s|CENSYS_API_KEY|${CENSYS_API_KEY}|g" |
    sed "s|CENSYS_SECRET|${CENSYS_SECRET}|g" |
    sed "s|GITHUB_API_KEY|${GITHUB_API_KEY}|g" |
    sed "s|INTELX_API_KEY|${INTELX_API_KEY}|g" |
    sed "s|INTELX_HOST|${INTELX_HOST}|g" |
    sed "s|PASSIVETOTAL_USERNAME|${PASSIVETOTAL_USERNAME}|g" |
    sed "s|PASSIVETOTAL_PASSWORD|${PASSIVETOTAL_PASSWORD}|g" |
    sed "s|RECONDEV_API_KEY|${RECONDEV_API_KEY}|g" |
    sed "s|SECURITYTRAILS_API_KEY|${SECURITYTRAILS_API_KEY}|g" |
    sed "s|SHODAN_API_KEY|${SHODAN_API_KEY}|g" |
    sed "s|SPYSE_API_KEY|${SPYSE_API_KEY}|g" |
    sed "s|URLSCAN_API_KEY|${URLSCAN_API_KEY}|g" |
    sed "s|VIRUSTOTAL_API_KEY|${VIRUSTOTAL_API_KEY}|g" |
    sed "s|ZOOMEYE_USERNAME|${ZOOMEYE_USERNAME}|g" |
    sed "s|ZOOMEYE_PASSWORD|${ZOOMEYE_PASSWORD}|g" >"${PATH_SUBFINDER_CONFIG}"
    exit 0
)}

uninstall() {
    rm -rf "${PATH_SUBFINDER_CONFIG}"
}
